In [65]:
import pandas as pd
import numpy as np

In [66]:
df = pd.read_csv('healthcare.csv')

In [100]:
X = df.drop(columns=['Id', 'Outcome'])
y = df['Outcome'].head(5)

In [101]:
X1 = X.head(5)
print(y)

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64


In [102]:
X1

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [103]:
X1 = X1.to_numpy()

In [104]:
X1

array([[6.000e+00, 1.480e+02, 7.200e+01, 3.500e+01, 0.000e+00, 3.360e+01,
        6.270e-01, 5.000e+01],
       [1.000e+00, 8.500e+01, 6.600e+01, 2.900e+01, 0.000e+00, 2.660e+01,
        3.510e-01, 3.100e+01],
       [8.000e+00, 1.830e+02, 6.400e+01, 0.000e+00, 0.000e+00, 2.330e+01,
        6.720e-01, 3.200e+01],
       [1.000e+00, 8.900e+01, 6.600e+01, 2.300e+01, 9.400e+01, 2.810e+01,
        1.670e-01, 2.100e+01],
       [0.000e+00, 1.370e+02, 4.000e+01, 3.500e+01, 1.680e+02, 4.310e+01,
        2.288e+00, 3.300e+01]])

In [105]:
feature_names = X.loc[:, :].columns.tolist()

In [123]:
def cal_entropy(node_indices):
        # calculate cross_entropy for that node
        entropy = 0
        if (len(node_indices) != 0):
            outs = y[node_indices] # filter indices 
            p_1 = len(outs[outs==1]) / len(node_indices) # calculating the probability that y=1
            if (p_1 == 1) or (p_1 == 0):
                entropy = 0
            else:
                entropy = -p_1*np.log2(p_1)-(1-p_1)*np.log2(1-p_1)
        return entropy

In [124]:
def compute_gain(left_indices, right_indices, num_examples, all_indices):
    w_left = len(left_indices) / num_examples
    w_right = len(right_indices) / num_examples
    
    left = w_left * cal_entropy(left_indices)
    right = w_right * cal_entropy(right_indices)
    
    gain = cal_entropy(all_indices) - (left + right)
    
    return gain
    
    
    
    
    
    

In [158]:
best_gain = 0
best_thresh = 0
best_feature = ""

for i, feature in enumerate(feature_names):
    vals = X1[:, i]
    all_indices = np.arange(X1.shape[0])
    total = np.unique(X1[:, i])
    for j, threshold in enumerate(total):
        curr_gain = 0
        curr_thresh = threshold
        left_indices = np.where(vals <= threshold)[0]
        right_indices = np.where(vals > threshold)[0]
        curr_gain = compute_gain(left_indices, right_indices, len(vals), all_indices)
        if (curr_gain > best_gain):
            best_gain = curr_gain
            best_thresh = curr_thresh
            best_feature = i
                

print(best_gain)
print(best_thresh)
print(best_feature)

0.9709505944546686
89.0
1


In [167]:

# split dataset does


left = np.where(X1[:, best_feature] <= best_thresh)[0]
right = np.where(X1[:, best_feature] > best_thresh)[0]
print(left)
print(right)







[1 3]
[0 2 4]


In [140]:
all_indices = np.arange(X1.shape[0])
print(all_indices)

[0 1 2 3 4]


In [141]:
cal_entropy(all_indices)

0.9709505944546686